### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by ElectroBoy404NotFound** [tvlad1234/pico-displayDrivs#3]
How to?

**Comment by tvlad1234** [comment]
read the readme

**Comment by ElectroBoy404NotFound** [comment]
@tvlad1234 Sorry, wrong repo

**Comment by tvlad1234** [comment]
No worries! Did you succeed to compile what you were trying to? Let me know if you need assistance with any of my repos.

**Comment by ElectroBoy404NotFound** [comment]
Yes, I did succeed what i wanted to compile. I was trying to compile your repo <a href="https://github.com/tvlad1234/pico-rv32ima">Linux on Pico</a>
